### ISSUE TITLE
[Question] How to deal with faulty commits?

### ISSUE THREAD

**Issue by SamMousa** [ahmadnassri/action-commit-lint#120]
If a contributor opens a PR containing (some) commits that don't pass the commitlint checks, how can they resolve?

They can't change the commit messages by adding more commits and having them redo the commits on a fresh branch seems like an extreme measure.

**Comment by ahmadnassri** [comment]
in my workflows with my team, I use the "Squash & Merge" approach to replace the commit message that ends up in the main branch. I use this as an educational opportunity to avoid mistakes in the future.

There are ways to change a commit message PRIOR to merging the PR:

- if only one commit: `git commit --amend -m "New commit message."` followed by `git push --force` on the PR branch
- if more than one commit: 
  - `git rebase -i HEAD~N`, where `N` is the number of commits to perform a rebase on.
  - edit the commit messages
  - `git push --force`

if you do this on the open PR before merging, you CAN overwrite commit messages.

> see this article for in-depth example: https://linuxize.com/post/change-git-commit-message/

**Comment by SamMousa** [comment]
Thanks, would this be something to add to the readme?

**Comment by ahmadnassri** [comment]
good idea ... do you wanna take a stab at it with a PR that includes all the steps like in the article?
